spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weather_service_db
    username: postgres
    password: postgres
  flyway:
    baselineOnMigrate: true
    enabled: true
    schemas: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none